### PR TITLE
Various fixes to the debugging page.

### PR DESCRIPTION
**Pull request by Hixie**

### CODE REVIEW

**Comment by abarth** [comment]
LGTM

**Comment by abarth** [comment]
[info] Unused import at example/debugging_md_1.dart, line 2.

**Comment by Hixie** [comment]
that unused import warning makes no sense to me. There's two dart blocks. One imports dart:developer and then calls debugger(), the other imports material and then uses MaterialApp.

**Comment by abarth** [comment]
I suspect the problem is that the script that generates the dart files also imports material.dart, which is unused in that block.  There's an annotation you can use to suppress the tool.

**Comment by Hixie** [comment]
Ohhh, yeah, that'll be it. Ok, I'll skip it for that block.

**Comment by Hixie** [comment]
Note for people confused about the StatisticsOverlay rename in this patch: I'm about to check in that rename in the engine and framework (tomorrow). It's just the docs being a little bit ahead of reality for once.

**Pull request merged**
