### PR TITLE
Validate snippets

### PR DESCRIPTION
**Pull request by devoncarew**
Validate the code snippets in the documentation. They drift out of date as the APIs get refactored; this will help keep them in sync.

- extract code snippets out into dart files in the `example/` dir
- add travis functionality to perform the extraction and analyze the code on PRs / commits
- add the ability to skip some dart snippets, or decorate them with hidden header code
- fix 1/2 dozen issues found in the snippets

There are 13 issues with the current snippets. We'll want to fix those issues or skip those snippets.

### CODE REVIEW

**Comment by devoncarew** [comment]
Merged with master; now only 5 issues remaining:

```
[warning] The method 'debugDumpRenderTree' is not defined for the class 'FlutterBinding' at example/rendering_md_1.dart, line 401.
[warning] The named parameter 'child' is not defined at example/tutorial_md_5.dart, line 220.
[warning] Undefined class 'ShrinkWrapWidth' at example/tutorial_md_5.dart, line 220.
[warning] The named parameter 'child' is not defined at example/tutorial_md_6.dart, line 299.
[warning] The named parameter 'child' is not defined at example/tutorial_md_7.dart, line 417.
```

**Comment by devoncarew** [comment]
@abarth for review

I'd also like to hook travis up to the repo, in order to analyze the code snippets on each commit / PR. If that sounds good, I'll do that after this is reviewed -

**Comment by abarth** [comment]
LGTM

Wow, this is great.  /cc @Hixie

**Comment by abarth** [comment]
I turned on Travis for this repo, in case that helps.

**Comment by Hixie** [comment]
nice!

**Comment by devoncarew** [comment]
Thanks! I'll land this and add a note about how to tweak the analysis from the markdown.

**Comment by sethladd** [comment]
This is excellent!

**Pull request merged**
