### PR TITLE
Fix typo for iOS version

### PR DESCRIPTION
**Pull request by sethladd**
specify iOS version correctly, clarify 5S or newer

### CODE REVIEW

**Comment by sethladd** [comment]
cc @chinmaygarde is this accurate?

**Comment by chinmaygarde** [comment]
We should probably just specify the OS version. So iOS 8. Should we mention that we can make builds for older OS versions if GN files are included and builds are initiated from the engine repo?

**Comment by sethladd** [comment]
I seem to remember something about 64 bit or 32 bit, which was the 5S+ comment. What should we say there?

**Comment by chinmaygarde** [comment]
We currently don't support universal builds. But we probably will soon. For now, we have a separate runner for armv7 and arm64

**Comment by sethladd** [comment]
What is the net-effect of not supporting universal builds for now? Does that limit which devices we can deploy to today? If so, which ones?

**Comment by sethladd** [comment]
TBR @chinmaygarde

**Comment by chinmaygarde** [comment]
Whoops. Sorry if you were waiting for an lgtm. Thought it was already updated. My bad.

**Pull request merged**
