### PR TITLE
be clear we are tech preview

### PR DESCRIPTION
**Pull request by sethladd**

### CODE REVIEW

**Comment by sethladd** [comment]
cc @Hixie

**Comment by Hixie** [comment]
"Technology preview" implies that it was hidden from view then shown. How about "is an early-stage open-source project. We are still missing core features like accessibility, text input, localisation, ..."?

**Comment by sethladd** [comment]
> implies that it was hidden from view then shown

Interesting. That's not the semantics that Google uses for "tech preview". But, if it's confusing, we'll change it.

**Comment by sethladd** [comment]
ptal thanks!

**Comment by abarth** [comment]
LGTM

**Pull request merged**
